services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:8.2.6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  mongo-data: