services:
  api:
    build: .
    container_name: bellarti_api
    command: daphne -b 0.0.0.0 -p 8000 api_sataiga.asgi:application
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: bellarti_celery
    command: celery -A api_sataiga worker --loglevel=info
    env_file:
      - .env.prod
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped