# Generated by Django 5.1.6 on 2025-04-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('supplier_id', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=34, null=True)),
                ('card_number', models.CharField(max_length=16, null=True)),
                ('clabe', models.CharField(max_length=18, null=True)),
                ('holder', models.CharField(max_length=100, null=True)),
                ('credit_term', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=25)),
                ('values', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('pe_id', models.PositiveSmallIntegerField(null=True)),
                ('type', models.CharField(choices=[('VS', 'Vivienda en Serie'), ('PE', 'Proyectos ESpeciales')], default='VS', max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('supplier_id', models.CharField(max_length=50)),
                ('name', models.TextField()),
                ('supplier_code', models.CharField(max_length=25, null=True)),
                ('area', models.CharField(choices=[('CONSUMO INTERNO', 'Consumo Interno'), ('OPERACIÓN', 'Operación')], max_length=25, null=True)),
                ('minimum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('maximum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('measurement', models.CharField(max_length=25)),
                ('presentation', models.CharField(max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('inventory_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('price_difference', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('automation', models.BooleanField(default=False)),
                ('images', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('front', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('supplier_id', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=25)),
                ('next_date', models.DateTimeField(null=True)),
                ('history', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=20)),
                ('permissions', models.JSONField(null=True)),
                ('icon', models.CharField(max_length=25, null=True)),
                ('status', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('parent', models.CharField(max_length=50)),
                ('level_1', models.CharField(max_length=50, null=True)),
                ('level_2', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('supplier_id', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('regime', models.CharField(max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=5, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('constancy', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('role_id', models.CharField(max_length=50)),
                ('role', models.JSONField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.PositiveSmallIntegerField()),
                ('avatar', models.TextField(null=True)),
                ('permissions', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volumetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=50)),
                ('front', models.CharField(max_length=100)),
                ('material_id', models.CharField(max_length=50)),
                ('volumetry', models.JSONField(null=True)),
                ('gran_total', models.FloatField(default=0)),
            ],
        ),
    ]
