from django.urls import path
from api.views import *

urlpatterns = [
    path('sections', SectionView.as_view(), name="sections"),
    path('tree-view-sections', TreeView.as_view(), name="treee_view_sections"),
    path('section/<str:id>', SectionViewById.as_view(), name="section"),
    path('roles', RoleView.as_view(), name="roles"),
    path('role/<str:id>', RoleByIdView.as_view(), name="role"),
    path('update-permissions/<str:id>',
         UpdatePermissionsView.as_view(), name="update_permissions"),
    path('users', UserView.as_view(), name='users'),
    path('user/<str:id>', UserByIdView.as_view(), name='user'),
    path('register/<str:id>', RegisterView.as_view(), name='register'),
    path('change-password/<str:id>',
         UpdatePasswordView.as_view(), name='update_password'),
    path('login', AuthView.as_view(), name='login'),
    path('password-request', PasswordRequestView.as_view(), name="password_request"),
    path('restore-password', RestorePasswordView.as_view(), name="restore_password"),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('clients', ClientView.as_view(), name='clients'),
    path('clients/<str:client_type>',
         ClientByTypeView.as_view(), name="client by type"),
    path('client/<str:id>', ClientByIdView.as_view(), name="client"),
    path('suppliers', SupplierView.as_view(), name='suppliers'),
    path('supplier/<str:id>', SupplierByIdView.as_view(), name='supplier'),
    path('prototypes', PrototypeView.as_view(), name='prototypes'),
    path('prototype/<str:id>', PrototypeByIdView.as_view(), name='prototype'),
    path('prototype_by_client/<str:client_id>',
         PrototypeByClientView.as_view(), name='prototype by client'),
    path('catalogs', CatalogView.as_view(), name="catalogs"),
    path('catalog/<str:id>', CatalogByIdView.as_view(), name='catalog'),
    path('materials', MatrialView.as_view(), name='materials'),
    path('material/<str:id>', MaterialByIdView.as_view(), name='material'),
    path('volumetries', VolumetryView.as_view(), name='volumetries'),
    path('volumetry/<str:id>', VolumetryByIdView.as_view(), name='volumetry'),
    path('upload_volumetry', VolumetryUploadView.as_view(), name="upload volumetry"),
    path('tax_data/supplier/<str:supplier_id>',
         TaxDataSupplierView.as_view(), name='tax data supplier'),
    path('tax_data/client/<str:client_id>',
         TaxDataClientView.as_view(), name='tax data client'),
    path('bank_data/<str:supplier_id>', BankDataView.as_view(), name='bank data'),
    path('refresh_rate/<str:supplier_id>',
         RefreshRateView.as_view(), name='refresh rate'),
    path('refresh_rates', RefreshRatesView.as_view(), name='refresh rates'),
    path('notifications', NotificationsView.as_view(), name='notifications'),
    path('exportar-materiales', DownloadMaterialsView.as_view(),
         name='exportar-materiales'),
    path('material-images/<str:id>',
         ImagesMaterialView.as_view(), name='material-images'),
    path('home-production', HomeProductionView.as_view(), name='home-production'),
    path('home-production/<str:id>', HomeProductionByIdView.as_view(),
         name='home-production-by-id'),
    path('lots/<str:home_production_id>', LotsView.as_view(), name='lots'),
    path('lot/<str:id>', LotView.as_view(), name="lot"),
    path('lots/<str:home_production_id>', LotsView.as_view(), name='lots'),
    path('explosion/<str:home_production_id>',
         ExplosionView.as_view(), name='explosion'),
    path('quantification', QuantificationView.as_view(), name='quantification'),
    path('quantification-filters', QuantificationFiltersView.as_view(),
         name='quantification-filters'),
    path('quantification/<str:id>/<str:action>', QuantificationByIdView.as_view(),
         name='quantification by id'),
    path('contacts/<str:client_id>', ContactsView.as_view(), name='contacts'),
    path('contact/<str:id>', ContactByIdView.as_view(), name='contact'),
]
