name: Bellarti API

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Deploy to server
              env:
                SSH_PASSWORD: ${{ secrets.SSH_KEY }}
              run: |
                sshpass -p "$SSH_PASSWORD" ssh -p 2222 vixenslt@ssh.web6.us.cloudlogin.co << EOF
                  cd /api_bellarti/api_sataiga
                  git pull
                EOF
              shell: bash
